### ISSUE TITLE
Publish message using PSSRedisClient

### ISSUE THREAD

**Issue by mn288** [perrystreetsoftware/PSSRedisClient#5]
Hello, I need help in how to publish a message. Can't find a syntax or documentation for it

**Comment by esilverberg** [comment]
All commands, including the `publish` command, use the `exec` method of the `RedisClient` class.

```
self.redisManager?.exec(command: "publish foo bar", completion: self.messageReceived);
```

You can simulate this by running the example, typing "publish foo bar" in the text field, then clicking on "Execute Command"

**Comment by viniterra** [comment]
Could you show me an example on how to publish a sentence?

I tried
self.redisManager?.exec(command: "publish foo \\"bar 123 bar\\"", completion: self.messageReceived);

But escaping like that is not working.

When I don't use space, the message is published:

self.redisManager?.exec(command: "publish foo \\"bar\\"", completion: self.messageReceived);

but on the redis client I receive "\\"bar\\"" instead of just "bar"

So I believe that kind of escaping isn't working, hence the space makes it an illegal statement.
